---
title: "p8105_hw5_zl2860"
author: "Zongchao Liu"
date: "11/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggsci)
```

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


# Problem 1

```{r}
fill_in<-
  function(vec){
    if(is.numeric(vec)){
      mean_vec = mean(vec, na.rm= TRUE) # mean is apprxiumated
      vec = replace_na(vec,round(mean_vec, digits = 1))
    }
    else if(is.character(vec)){
      vec = replace_na(vec, "virginica")
    }
  }

data_filled <-
  map_df(iris_with_missing, fill_in)

```

# Problem 2 

## Tidy the data

```{r, message=FALSE, warning=FALSE}
file_names = list.files("./data/")

study_data <-
  tibble( file_names = file_names) %>%
  bind_cols(map_df(str_c("./data/", file_names), read_csv)) %>%
  separate(file_names, into = c("arm", "id"))

data_con <- 
  study_data %>%
  filter(arm == "con")

data_con %>%
  knitr::kable()
```

## Make a Spaghetti Plot

```{r}
study_data %>%
  pivot_longer( week_1 : week_8,
                names_to = "week",
                names_prefix = "week_",
               values_to = "observations") %>%
  mutate(arm_id = str_c(arm,id)) %>%
  ggplot(aes( x = week, y = observations, color = arm, group = arm_id)) +
  geom_line() +
  ggsci::scale_color_jco() +
  theme_bw() +
  labs( title = "A Spaghetti Plot showing observations on each subject over time",
        x = "Week",
        y = "Observations") +
  theme(plot.title = element_text(hjust = .5))
```


From the plot above, we see that the average observation on the subjects in experimental arm is higher than that on the subjects in control arm. Also, over the 8 weeks, the observations on the subjects in experimental arm have an increasing trend while the observations in control arm fluctuate within a range.



